### PR TITLE
feat: 🎸 added react hooks linting rules

### PR DESCRIPTION
**Pull request by diogofcunha**
added react hooks linting rules. This small plugin will give us some
hints about respecting "rules of hooks"
(https://reactjs.org/docs/hooks-rules.html), the general community
feeling about this plugin is that it prevents massive bugs and gotchas
while using this new api

### CODE REVIEW

**Comment by jasoniangreen** [comment]
Yeah, I agree with @ForbesLindesay, I like the fact that we have all our own rules set explicitly. I'm happy to just rip out whatever it is we are extending.

**Comment by ForbesLindesay** [comment]
As I said, we're not using that react.js file anywhere, as far as I'm aware.

**Comment by diogofcunha** [comment]
@ForbesLindesay we are using react.js on storymaker. I don't believe having react and other linting rules separate is an issue at all. This way we can include those rules if we use react in the project and opt out if we don't. What we could do is be more specific about the react rules we want to specify but that's out of scope for this PR where I just want to get a basic help in the code I'm writing on storymaker right now.

The original eslint package contains 2 rules and that's specified in the package in questions, both rules have links to details in the readme and they both looks sensible things to have:
```
"react-hooks/rules-of-hooks": "error",
"react-hooks/exhaustive-deps": "warn"
```

as this is **tslint** and not eslint the package added in this PR **only has the first rule (equivalent to `react-hooks/rules-of-hooks`)**, that is also specified in the readme for the package, the default for the rule is "error" and that seems sensible to me.

**Comment by diogofcunha** [comment]
I've added ` 'react-hooks-nesting': 'error'` to react rules

**Pull request closed without merging**
